// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATASTOREDOWNLOADRESPONSE1_TEO_DATASTOREDOWNLOAD_H_
#define FLATBUFFERS_GENERATED_DATASTOREDOWNLOADRESPONSE1_TEO_DATASTOREDOWNLOAD_H_

#include "flatbuffers/flatbuffers.h"

namespace teo {
namespace DataStoreDownload {

struct OwnerPubkey;
struct OwnerPubkeyBuilder;

struct DataStoreDownloadResponse1;
struct DataStoreDownloadResponse1Builder;

struct OwnerPubkey FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef OwnerPubkeyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PK = 4
  };
  const flatbuffers::Vector<uint8_t> *pk() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_PK);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PK) &&
           verifier.VerifyVector(pk()) &&
           verifier.EndTable();
  }
};

struct OwnerPubkeyBuilder {
  typedef OwnerPubkey Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_pk(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> pk) {
    fbb_.AddOffset(OwnerPubkey::VT_PK, pk);
  }
  explicit OwnerPubkeyBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<OwnerPubkey> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<OwnerPubkey>(end);
    return o;
  }
};

inline flatbuffers::Offset<OwnerPubkey> CreateOwnerPubkey(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> pk = 0) {
  OwnerPubkeyBuilder builder_(_fbb);
  builder_.add_pk(pk);
  return builder_.Finish();
}

inline flatbuffers::Offset<OwnerPubkey> CreateOwnerPubkeyDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *pk = nullptr) {
  auto pk__ = pk ? _fbb.CreateVector<uint8_t>(*pk) : 0;
  return teo::DataStoreDownload::CreateOwnerPubkey(
      _fbb,
      pk__);
}

struct DataStoreDownloadResponse1 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef DataStoreDownloadResponse1Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OWNER_PUBKEYS = 4,
    VT_CONTENT_LEN = 6
  };
  const flatbuffers::Vector<flatbuffers::Offset<teo::DataStoreDownload::OwnerPubkey>> *owner_pubkeys() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<teo::DataStoreDownload::OwnerPubkey>> *>(VT_OWNER_PUBKEYS);
  }
  int32_t content_len() const {
    return GetField<int32_t>(VT_CONTENT_LEN, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OWNER_PUBKEYS) &&
           verifier.VerifyVector(owner_pubkeys()) &&
           verifier.VerifyVectorOfTables(owner_pubkeys()) &&
           VerifyField<int32_t>(verifier, VT_CONTENT_LEN) &&
           verifier.EndTable();
  }
};

struct DataStoreDownloadResponse1Builder {
  typedef DataStoreDownloadResponse1 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_owner_pubkeys(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<teo::DataStoreDownload::OwnerPubkey>>> owner_pubkeys) {
    fbb_.AddOffset(DataStoreDownloadResponse1::VT_OWNER_PUBKEYS, owner_pubkeys);
  }
  void add_content_len(int32_t content_len) {
    fbb_.AddElement<int32_t>(DataStoreDownloadResponse1::VT_CONTENT_LEN, content_len, 0);
  }
  explicit DataStoreDownloadResponse1Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<DataStoreDownloadResponse1> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<DataStoreDownloadResponse1>(end);
    return o;
  }
};

inline flatbuffers::Offset<DataStoreDownloadResponse1> CreateDataStoreDownloadResponse1(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<teo::DataStoreDownload::OwnerPubkey>>> owner_pubkeys = 0,
    int32_t content_len = 0) {
  DataStoreDownloadResponse1Builder builder_(_fbb);
  builder_.add_content_len(content_len);
  builder_.add_owner_pubkeys(owner_pubkeys);
  return builder_.Finish();
}

inline flatbuffers::Offset<DataStoreDownloadResponse1> CreateDataStoreDownloadResponse1Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<teo::DataStoreDownload::OwnerPubkey>> *owner_pubkeys = nullptr,
    int32_t content_len = 0) {
  auto owner_pubkeys__ = owner_pubkeys ? _fbb.CreateVector<flatbuffers::Offset<teo::DataStoreDownload::OwnerPubkey>>(*owner_pubkeys) : 0;
  return teo::DataStoreDownload::CreateDataStoreDownloadResponse1(
      _fbb,
      owner_pubkeys__,
      content_len);
}

inline const teo::DataStoreDownload::DataStoreDownloadResponse1 *GetDataStoreDownloadResponse1(const void *buf) {
  return flatbuffers::GetRoot<teo::DataStoreDownload::DataStoreDownloadResponse1>(buf);
}

inline const teo::DataStoreDownload::DataStoreDownloadResponse1 *GetSizePrefixedDataStoreDownloadResponse1(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<teo::DataStoreDownload::DataStoreDownloadResponse1>(buf);
}

inline bool VerifyDataStoreDownloadResponse1Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<teo::DataStoreDownload::DataStoreDownloadResponse1>(nullptr);
}

inline bool VerifySizePrefixedDataStoreDownloadResponse1Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<teo::DataStoreDownload::DataStoreDownloadResponse1>(nullptr);
}

inline void FinishDataStoreDownloadResponse1Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::DataStoreDownload::DataStoreDownloadResponse1> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDataStoreDownloadResponse1Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::DataStoreDownload::DataStoreDownloadResponse1> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace DataStoreDownload
}  // namespace teo

#endif  // FLATBUFFERS_GENERATED_DATASTOREDOWNLOADRESPONSE1_TEO_DATASTOREDOWNLOAD_H_
