// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_INITIALIZATIONDEVICEINFO_TEO_H_
#define FLATBUFFERS_GENERATED_INITIALIZATIONDEVICEINFO_TEO_H_

#include "flatbuffers/flatbuffers.h"

namespace teo {

struct InitializationDeviceInfo;
struct InitializationDeviceInfoBuilder;

struct InitializationDeviceInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef InitializationDeviceInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CIPHERTEXT = 4
  };
  const flatbuffers::Vector<uint8_t> *ciphertext() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_CIPHERTEXT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CIPHERTEXT) &&
           verifier.VerifyVector(ciphertext()) &&
           verifier.EndTable();
  }
};

struct InitializationDeviceInfoBuilder {
  typedef InitializationDeviceInfo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_ciphertext(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> ciphertext) {
    fbb_.AddOffset(InitializationDeviceInfo::VT_CIPHERTEXT, ciphertext);
  }
  explicit InitializationDeviceInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<InitializationDeviceInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<InitializationDeviceInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<InitializationDeviceInfo> CreateInitializationDeviceInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> ciphertext = 0) {
  InitializationDeviceInfoBuilder builder_(_fbb);
  builder_.add_ciphertext(ciphertext);
  return builder_.Finish();
}

inline flatbuffers::Offset<InitializationDeviceInfo> CreateInitializationDeviceInfoDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *ciphertext = nullptr) {
  auto ciphertext__ = ciphertext ? _fbb.CreateVector<uint8_t>(*ciphertext) : 0;
  return teo::CreateInitializationDeviceInfo(
      _fbb,
      ciphertext__);
}

inline const teo::InitializationDeviceInfo *GetInitializationDeviceInfo(const void *buf) {
  return flatbuffers::GetRoot<teo::InitializationDeviceInfo>(buf);
}

inline const teo::InitializationDeviceInfo *GetSizePrefixedInitializationDeviceInfo(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<teo::InitializationDeviceInfo>(buf);
}

inline bool VerifyInitializationDeviceInfoBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<teo::InitializationDeviceInfo>(nullptr);
}

inline bool VerifySizePrefixedInitializationDeviceInfoBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<teo::InitializationDeviceInfo>(nullptr);
}

inline void FinishInitializationDeviceInfoBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::InitializationDeviceInfo> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedInitializationDeviceInfoBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::InitializationDeviceInfo> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace teo

#endif  // FLATBUFFERS_GENERATED_INITIALIZATIONDEVICEINFO_TEO_H_
