// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_INITIALIZATIONREQUEST_TEO_H_
#define FLATBUFFERS_GENERATED_INITIALIZATIONREQUEST_TEO_H_

#include "flatbuffers/flatbuffers.h"

namespace teo {

struct InitializationRequest;
struct InitializationRequestBuilder;

struct InitializationRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef InitializationRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SETUP_HEADER = 4,
    VT_CIPHERTEXT = 6
  };
  const flatbuffers::Vector<uint8_t> *setup_header() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_SETUP_HEADER);
  }
  const flatbuffers::Vector<uint8_t> *ciphertext() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_CIPHERTEXT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SETUP_HEADER) &&
           verifier.VerifyVector(setup_header()) &&
           VerifyOffset(verifier, VT_CIPHERTEXT) &&
           verifier.VerifyVector(ciphertext()) &&
           verifier.EndTable();
  }
};

struct InitializationRequestBuilder {
  typedef InitializationRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_setup_header(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> setup_header) {
    fbb_.AddOffset(InitializationRequest::VT_SETUP_HEADER, setup_header);
  }
  void add_ciphertext(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> ciphertext) {
    fbb_.AddOffset(InitializationRequest::VT_CIPHERTEXT, ciphertext);
  }
  explicit InitializationRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<InitializationRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<InitializationRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<InitializationRequest> CreateInitializationRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> setup_header = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> ciphertext = 0) {
  InitializationRequestBuilder builder_(_fbb);
  builder_.add_ciphertext(ciphertext);
  builder_.add_setup_header(setup_header);
  return builder_.Finish();
}

inline flatbuffers::Offset<InitializationRequest> CreateInitializationRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *setup_header = nullptr,
    const std::vector<uint8_t> *ciphertext = nullptr) {
  auto setup_header__ = setup_header ? _fbb.CreateVector<uint8_t>(*setup_header) : 0;
  auto ciphertext__ = ciphertext ? _fbb.CreateVector<uint8_t>(*ciphertext) : 0;
  return teo::CreateInitializationRequest(
      _fbb,
      setup_header__,
      ciphertext__);
}

inline const teo::InitializationRequest *GetInitializationRequest(const void *buf) {
  return flatbuffers::GetRoot<teo::InitializationRequest>(buf);
}

inline const teo::InitializationRequest *GetSizePrefixedInitializationRequest(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<teo::InitializationRequest>(buf);
}

inline bool VerifyInitializationRequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<teo::InitializationRequest>(nullptr);
}

inline bool VerifySizePrefixedInitializationRequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<teo::InitializationRequest>(nullptr);
}

inline void FinishInitializationRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::InitializationRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedInitializationRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::InitializationRequest> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace teo

#endif  // FLATBUFFERS_GENERATED_INITIALIZATIONREQUEST_TEO_H_
