// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_UTILREMOVEREALTIMEACCESS_TEO_H_
#define FLATBUFFERS_GENERATED_UTILREMOVEREALTIMEACCESS_TEO_H_

#include "flatbuffers/flatbuffers.h"

namespace teo {

struct UtilRemoveRealTimeAccess;
struct UtilRemoveRealTimeAccessBuilder;

struct UtilRemoveRealTimeAccess FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UtilRemoveRealTimeAccessBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USER_PUBKEY = 4
  };
  const flatbuffers::Vector<uint8_t> *user_pubkey() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_USER_PUBKEY);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_USER_PUBKEY) &&
           verifier.VerifyVector(user_pubkey()) &&
           verifier.EndTable();
  }
};

struct UtilRemoveRealTimeAccessBuilder {
  typedef UtilRemoveRealTimeAccess Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_user_pubkey(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> user_pubkey) {
    fbb_.AddOffset(UtilRemoveRealTimeAccess::VT_USER_PUBKEY, user_pubkey);
  }
  explicit UtilRemoveRealTimeAccessBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<UtilRemoveRealTimeAccess> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UtilRemoveRealTimeAccess>(end);
    return o;
  }
};

inline flatbuffers::Offset<UtilRemoveRealTimeAccess> CreateUtilRemoveRealTimeAccess(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> user_pubkey = 0) {
  UtilRemoveRealTimeAccessBuilder builder_(_fbb);
  builder_.add_user_pubkey(user_pubkey);
  return builder_.Finish();
}

inline flatbuffers::Offset<UtilRemoveRealTimeAccess> CreateUtilRemoveRealTimeAccessDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *user_pubkey = nullptr) {
  auto user_pubkey__ = user_pubkey ? _fbb.CreateVector<uint8_t>(*user_pubkey) : 0;
  return teo::CreateUtilRemoveRealTimeAccess(
      _fbb,
      user_pubkey__);
}

inline const teo::UtilRemoveRealTimeAccess *GetUtilRemoveRealTimeAccess(const void *buf) {
  return flatbuffers::GetRoot<teo::UtilRemoveRealTimeAccess>(buf);
}

inline const teo::UtilRemoveRealTimeAccess *GetSizePrefixedUtilRemoveRealTimeAccess(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<teo::UtilRemoveRealTimeAccess>(buf);
}

inline bool VerifyUtilRemoveRealTimeAccessBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<teo::UtilRemoveRealTimeAccess>(nullptr);
}

inline bool VerifySizePrefixedUtilRemoveRealTimeAccessBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<teo::UtilRemoveRealTimeAccess>(nullptr);
}

inline void FinishUtilRemoveRealTimeAccessBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::UtilRemoveRealTimeAccess> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedUtilRemoveRealTimeAccessBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::UtilRemoveRealTimeAccess> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace teo

#endif  // FLATBUFFERS_GENERATED_UTILREMOVEREALTIMEACCESS_TEO_H_
