// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_UTILFETCHIPREQUEST_TEO_H_
#define FLATBUFFERS_GENERATED_UTILFETCHIPREQUEST_TEO_H_

#include "flatbuffers/flatbuffers.h"

namespace teo {

struct UtilFetchIpRequest;
struct UtilFetchIpRequestBuilder;

struct UtilFetchIpRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UtilFetchIpRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PUBKEY = 4
  };
  const flatbuffers::Vector<uint8_t> *pubkey() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_PUBKEY);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PUBKEY) &&
           verifier.VerifyVector(pubkey()) &&
           verifier.EndTable();
  }
};

struct UtilFetchIpRequestBuilder {
  typedef UtilFetchIpRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_pubkey(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> pubkey) {
    fbb_.AddOffset(UtilFetchIpRequest::VT_PUBKEY, pubkey);
  }
  explicit UtilFetchIpRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<UtilFetchIpRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UtilFetchIpRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<UtilFetchIpRequest> CreateUtilFetchIpRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> pubkey = 0) {
  UtilFetchIpRequestBuilder builder_(_fbb);
  builder_.add_pubkey(pubkey);
  return builder_.Finish();
}

inline flatbuffers::Offset<UtilFetchIpRequest> CreateUtilFetchIpRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *pubkey = nullptr) {
  auto pubkey__ = pubkey ? _fbb.CreateVector<uint8_t>(*pubkey) : 0;
  return teo::CreateUtilFetchIpRequest(
      _fbb,
      pubkey__);
}

inline const teo::UtilFetchIpRequest *GetUtilFetchIpRequest(const void *buf) {
  return flatbuffers::GetRoot<teo::UtilFetchIpRequest>(buf);
}

inline const teo::UtilFetchIpRequest *GetSizePrefixedUtilFetchIpRequest(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<teo::UtilFetchIpRequest>(buf);
}

inline bool VerifyUtilFetchIpRequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<teo::UtilFetchIpRequest>(nullptr);
}

inline bool VerifySizePrefixedUtilFetchIpRequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<teo::UtilFetchIpRequest>(nullptr);
}

inline void FinishUtilFetchIpRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::UtilFetchIpRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedUtilFetchIpRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::UtilFetchIpRequest> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace teo

#endif  // FLATBUFFERS_GENERATED_UTILFETCHIPREQUEST_TEO_H_
