// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_UTILREALTIMEACCESSREQUEST_TEO_H_
#define FLATBUFFERS_GENERATED_UTILREALTIMEACCESSREQUEST_TEO_H_

#include "flatbuffers/flatbuffers.h"

namespace teo {

struct UtilRealTimeAccessRequest;
struct UtilRealTimeAccessRequestBuilder;

struct UtilRealTimeAccessRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UtilRealTimeAccessRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PUBKEY = 4
  };
  const flatbuffers::Vector<uint8_t> *pubkey() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_PUBKEY);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PUBKEY) &&
           verifier.VerifyVector(pubkey()) &&
           verifier.EndTable();
  }
};

struct UtilRealTimeAccessRequestBuilder {
  typedef UtilRealTimeAccessRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_pubkey(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> pubkey) {
    fbb_.AddOffset(UtilRealTimeAccessRequest::VT_PUBKEY, pubkey);
  }
  explicit UtilRealTimeAccessRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<UtilRealTimeAccessRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UtilRealTimeAccessRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<UtilRealTimeAccessRequest> CreateUtilRealTimeAccessRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> pubkey = 0) {
  UtilRealTimeAccessRequestBuilder builder_(_fbb);
  builder_.add_pubkey(pubkey);
  return builder_.Finish();
}

inline flatbuffers::Offset<UtilRealTimeAccessRequest> CreateUtilRealTimeAccessRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *pubkey = nullptr) {
  auto pubkey__ = pubkey ? _fbb.CreateVector<uint8_t>(*pubkey) : 0;
  return teo::CreateUtilRealTimeAccessRequest(
      _fbb,
      pubkey__);
}

inline const teo::UtilRealTimeAccessRequest *GetUtilRealTimeAccessRequest(const void *buf) {
  return flatbuffers::GetRoot<teo::UtilRealTimeAccessRequest>(buf);
}

inline const teo::UtilRealTimeAccessRequest *GetSizePrefixedUtilRealTimeAccessRequest(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<teo::UtilRealTimeAccessRequest>(buf);
}

inline bool VerifyUtilRealTimeAccessRequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<teo::UtilRealTimeAccessRequest>(nullptr);
}

inline bool VerifySizePrefixedUtilRealTimeAccessRequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<teo::UtilRealTimeAccessRequest>(nullptr);
}

inline void FinishUtilRealTimeAccessRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::UtilRealTimeAccessRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedUtilRealTimeAccessRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<teo::UtilRealTimeAccessRequest> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace teo

#endif  // FLATBUFFERS_GENERATED_UTILREALTIMEACCESSREQUEST_TEO_H_
